# Generated by Django 3.0.5 on 2020-04-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proj_dir', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
